// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjaU5iAWKTcU5ibXYcm2hAcStD7j5-vhc',
    appId: '1:184480230757:web:fb1af3ee7532598b05458c',
    messagingSenderId: '184480230757',
    projectId: 'koitai-app',
    authDomain: 'koitai-app.firebaseapp.com',
    storageBucket: 'koitai-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABXLzns9p6kh4GSUcGLEQdiflc6y2Q1OY',
    appId: '1:184480230757:android:280634fbd8413c8e05458c',
    messagingSenderId: '184480230757',
    projectId: 'koitai-app',
    storageBucket: 'koitai-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWCEqFt4C6_qnLcO2Y4ChnP0fj4I2MO2c',
    appId: '1:184480230757:ios:43f172e61c6d5a1a05458c',
    messagingSenderId: '184480230757',
    projectId: 'koitai-app',
    storageBucket: 'koitai-app.firebasestorage.app',
    iosBundleId: 'com.koitai.koitai',
  );
}
